Create workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,20 +5,14 @@ on:
     branches:
       - main
     paths:
-      - 'src/**'
       - 'public/**'
+      - 'src/**'
+      - 'services/**'
       - 'composer.json'
       - 'composer.lock'
       - 'package.json'
       - 'package-lock.json'
       - '.github/workflows/**'
-
-env:
-  AWS_REGION: us-west-2
-  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
-  APP_PATH: /var/www/html
-  SESSION_NAME: deploy-${{ github.run_id }}-${{ github.run_attempt }}
-  PHP_VERSION: 8.3
 
 permissions:
   id-token: write
@@ -28,9 +22,34 @@ jobs:
   lint:
     runs-on: ubuntu-22.04
 
+    env:
+      PHP_VERSION: 8.3
+      NODE_VERSION: 20.x
+
     steps:
       - name: Check out code
         uses: actions/checkout@v4
+
+      - name: Use Node.js 20.x 🛎
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+          cache: 'npm'
+
+      - name: Cache node modules 📦
+        id: cache-npm
+        uses: actions/cache@v4
+        with:
+          path: |
+            node_modules
+            ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+            ${{ runner.os }}-
+
+      - name: Install dependencies ⏳
+        run: npm ci
 
       - name: Use PHP 8.3 🛎
         uses: shivammathur/setup-php@v2
@@ -62,9 +81,15 @@ jobs:
   build-and-push-docker-image:
     needs: lint
     runs-on: ubuntu-22.04
+
+    env:
+      DOCKERHUB_USERNAME: tkwonn
+
     steps:
       - name: Check out code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Login to Docker Hub 🐳
         uses: docker/login-action@v3
@@ -72,13 +97,23 @@ jobs:
           username: ${{ env.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push Docker image 🚀
+      - name: Build and push Docker image PHP 🚀
         uses: docker/build-push-action@v5
         with:
           context: .
           file: ./services/prod/php/Dockerfile
           push: true
-          tags: ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:${{ github.sha }}
+          tags: ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:php-${{ github.sha }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Build and push Docker image Nginx 🚀
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./services/prod/nginx/Dockerfile
+          push: true
+          tags: ${{ env.DOCKERHUB_USERNAME }}/imgdock-prod:nginx-${{ github.sha }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
@@ -90,14 +125,14 @@ jobs:
       id-token: write
       contents: read
 
-      env:
-        ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
-        SESSION_NAME: deploy-${{ github.run_id }}-${{ github.run_attempt }}
-        GITHUB_BRANCH: "${{ github.ref_name }}"
+    env:
+      AWS_REGION: us-west-2
+      ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
+      SESSION_NAME: deploy-${{ github.run_id }}-${{ github.run_attempt }}
+      GITHUB_BRANCH: "${{ github.ref_name }}"
 
     steps:
-      # Checkout needed for deploy script
-      - name: Checkout code for deploy script
+      - name: Checkout for deploy script
         uses: actions/checkout@v4
 
       - name: Configure AWS credentials
@@ -109,28 +144,53 @@ jobs:
 
       - name: Deploy Application 🚀
         run: |
-          COMMANDS_JSON=$(cat << EOF
-          {
-           "commands": [
-             "set -e",
-             "sudo chown -R ubuntu:ubuntu /home/ubuntu/web/imgdock",
-             "sudo -u ubuntu bash -c \"cd /home/ubuntu/web/imgdock && \\
-               if [ -d /home/ubuntu/web/imgdock ]; then \\
-                 cd /home/ubuntu/web/imgdock && \\
-                 sudo docker stop \\\$(sudo docker ps -q) && \\
-                 sudo docker compose -f compose-prod.yml down && \\
-                 sudo docker system prune -af; \\
-               fi && \\
-               git pull origin $GITHUB_BRANCH && \\
-               sudo docker compose -f compose-prod.yml pull && \\
-               sudo docker compose -f compose-prod.yml up -d\""
-           ]
-          }
+          cat << EOF > deploy_commands.sh
+          #!/usr/bin/env bash
+          set -e
+
+          # 1) Cleanup docker and repository
+          chmod +x /home/ubuntu/web/imgdock/src/bin/cleanup.sh
+          /home/ubuntu/web/imgdock/src/bin/cleanup.sh
+
+          # 2) New repository clone
+          cd /home/ubuntu/web
+          git clone --branch $GITHUB_BRANCH
+          
+          # 3) .env setup
+          chmod +x /home/ubuntu/web/imgdock/src/bin/setup_env.sh
+          export APP_ENV=prod
+          export CLOUDFRONT_DOMAIN="${{ secrets.CLOUDFRONT_DOMAIN }}"
+          export VITE_BASE_URL="${{ secrets.VITE_BASE_URL }}"
+          export S3_BUCKET_NAME="imgdock-prod-storage"
+          export DATABASE_HOST="${{ secrets.DATABASE_HOST }}"
+          export DATABASE_NAME="imgdock"
+          export DATABASE_USER="${{ secrets.DATABASE_USER }}"
+          export DATABASE_USER_PASSWORD="${{ secrets.DATABASE_USER_PASSWORD }}"
+          export MEMCACHED_HOST="${{ secrets.MEMCACHED_HOST }}"
+          export MEMCACHED_PORT="${{ secrets.MEMCACHED_PORT }}"
+          
+          /home/ubuntu/web/imgdock/src/bin/setup_env.sh
+          
+          # 4) Pull image from Docker Hub and run containers
+          cd /home/ubuntu/web/imgdock
+          sudo docker compose -f compose-prod.yml up -d --pull always
           EOF
+          
+          chmod +x deploy_commands.sh
+          
+          COMMANDS_JSON=$(cat << EOCMD
+          {
+              "commands": [
+                "sudo chown ubuntu:ubuntu ./deploy_commands.sh",
+                "sudo -u ubuntu bash -c './deploy_commands.sh'"
+              ]
+          }
+          EOCMD
           )
           
+          # Send SSM Command
           COMMAND_ID=$(aws ssm send-command \
-            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
+            --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
             --document-name "AWS-RunShellScript" \
             --comment "Deploy application" \
             --parameters "$COMMANDS_JSON" \
@@ -139,7 +199,29 @@ jobs:
             --query "Command.CommandId" \
             --output text)
           
+          echo "SSM Command ID: $COMMAND_ID"
+          
+          # Wait for the command to finish
           aws ssm wait command-executed \
             --command-id "$COMMAND_ID" \
-            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
-            --region "${{ env.AWS_REGION }}
+            --instance-id "${{ env.EC2_INSTANCE_ID }}" \
+            --region "${{ env.AWS_REGION }}" || {
+              echo "SSM command failed or timed out."
+              aws ssm get-command-invocation \
+                --instance-id "${{ env.EC2_INSTANCE_ID }}" \
+                --command-id "$COMMAND_ID" \
+                --region "${{ env.AWS_REGION }}" \
+                --query "StandardErrorContent" \
+                --output text
+              exit 1
+            }
+
+          # Get the command output
+          OUTPUT=$(aws ssm get-command-invocation \
+            --instance-id "${{ env.EC2_INSTANCE_ID }}" \
+            --command-id "$COMMAND_ID" \
+            --region "${{ env.AWS_REGION }}" \
+            --query "StandardOutputContent" \
+            --output text)
+
+          echo "$OUTPUT"
